config/routes.rb
OnfireServer::Application.routes.draw do
  resources :parties

end

app/models/party.rb
class Party < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  # GET /parties
  # GET /parties.json
  def index
    longitude = params[:longitude]
    latitude = params[:latitude]
    if longitude && latitude
    @parties = Party.order("((parties.longitude - #{longitude})*(parties.longitude - #{longitude}))+((parties.latitude - #{latitude})*(parties.latitude - #{latitude})) ASC")
    else
    @parties = Party.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.json
  def new
    @party = Party.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(params[:party])

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render json: @party, status: :created, location: @party }
      else
        format.html { render action: "new" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.json
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnfireServer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td><%= party.name %></td>
    <td><%= party.latitude %></td>
    <td><%= party.longitude %></td>
    <td><%= party.score %></td>
    <td><%= link_to 'Show', party %></td>
    <td><%= link_to 'Edit', edit_party_path(party) %></td>
    <td><%= link_to 'Destroy', party, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @party.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @party.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @party.longitude %>
</p>

<p>
  <b>Score:</b>
  <%= @party.score %>
</p>


<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>